If you generated your app using the the Vue profile from the forge you can skip this step. If you created your
Vue.js application using the instructions found https://vuejs.org/v2/guide/installation.html[here] then you
will need to update your running port number as it will conflict with the server port. Switch your port from the
default `8080` to `3000` or choose your own port if you like, just make sure nothing is running on the port first.

[source, javascript]
./client/config/index.js
----
include::{sourceDir}/client/config/index.js[indent=0, tags=clientPort]
----

In addition to changing the port we need to add a few dependencies to our application as we are making use of
the new Bootstrap v4 as a test run. Add the following dependencies to `package.json` in the `devDependencies`
block.

[source, json]
./client/package.json
----
"bootstrap-vue": "^0.20.1",
"bootstrap": "^4.0.0-alpha.6",
"style-loader": "^0.18.2",
----

For more information on the `bootstrap-vue` project check out https://bootstrap-vue.js.org[Bootstrap + Vue documentation].
Now that we have included the bootstrap framework in our project we need to make it accessible to our components.
To use our new bootstrap library include the following in our `client/src/main.js`.

[source,javascript]
./client/src/main.js
----
include::{sourceDir}/client/src/main.js[]
----
<1> Include the three necessary imports to use bootstrap in our application
<2> Tell Vue.js to use bootstrap
<3> If you enabled es-lint allow the use of the `new` keyword

The `main.js` is the entry point into our Vue.js application and it imports our top level `App.vue`. Including
the above imports and `use` function are the only edits we will need to make to our `main.js` but we will revisit
our `App.vue` in a little bit.