Let's start by creating our domain model for the application.

[source,bash]
----
$ grails create-domain-class demo.Vehicle
$ grails create-domain-class demo.Driver
$ grails create-domain-class demo.Make
$ grails create-domain-class demo.Model
----

Now let's edit our domain class under `grails-app/domain/demo/`. We'll add some properties and the `@Resource` annotation.

[source,groovy]
.server/grails-app/domain/demo/Vehicle.groovy
----
include::{sourceDir}/server/grails-app/domain/demo/Vehicle.groovy[]
----

[source,groovy]
.server/grails-app/domain/demo/Driver.groovy
----
include::{sourceDir}/server/grails-app/domain/demo/Driver.groovy[]
----

[source,groovy]
.server/grails-app/domain/demo/Make.groovy
----
include::{sourceDir}/server/grails-app/domain/demo/Make.groovy[]
----

[source,groovy]
.server/grails-app/domain/demo/Model.groovy
----
include::{sourceDir}/server/grails-app/domain/demo/Model.groovy[]
----

Since we've added the `@Resource` annotation to our domain classes, Grails will generate RESTful URL mappings for each of them. 

Let's preload some data with the help of http://gorm.grails.org/latest/hibernate/manual/index.html#dataServices[GORM Data Services].


[source,groovy]
.server/grails-app/services/demo/MakeDataService.groovy
----
include::{sourceDir}/server/grails-app/services/demo/MakeDataService.groovy[]
----

[source,groovy]
.server/grails-app/services/demo/ModelDataService.groovy
----
include::{sourceDir}/server/grails-app/services/demo/ModelDataService.groovy[]
----

[source,groovy]
.server/grails-app/services/demo/DriverDataService.groovy
----
include::{sourceDir}/server/grails-app/services/demo/DriverDataService.groovy[]
----

[source,groovy]
.server/grails-app/services/demo/VehicleDataService.groovy
----
include::{sourceDir}/server/grails-app/services/demo/VehicleDataService.groovy[]
----

[source,groovy]
.server/grails-app/init/demo/BootStrap.groovy
----
include::{sourceDir}/server/grails-app/init/demo/BootStrap.groovy[]
----
